FROM node:22.13.1-slim

WORKDIR /app

# Install dependencies for development
COPY package.json package-lock.json ./
RUN npm install

# Set environment variables
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000

# Expose port
EXPOSE 3000

# Use nodemon for hot reloading (optional)
CMD ["npm", "run", "dev"]
